// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TUTOR.Repository.EF
{
    public partial class AdminManage
    {
        public int Id { get; set; }
        public string Account { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public int AdminLevel { get; set; }
        public DateTime CreateDate { get; set; }
        public int Status { get; set; }
        public string Jwttoken { get; set; }
    }
}