// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TUTOR.Repository.EF
{
    public partial class ApiTokenManage
    {
        public int Id { get; set; }
        public string ApiToken { get; set; }
        public int? TokenActive { get; set; }
        public DateTime? TokenStartTime { get; set; }
        public DateTime? TokenEndTime { get; set; }
        public string Ip { get; set; }
    }
}