// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TUTOR.Repository.EF
{
    public partial class GameWords
    {
        public int Id { get; set; }
        public string Word { get; set; }
        public int? HardLevel { get; set; }
        public int? Status { get; set; }
        public string WordKind { get; set; }
        public string Mp3Url { get; set; }
        public string WordChinese { get; set; }
    }
}