// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TUTOR.Repository.EF
{
    public partial class GamerWordsLog
    {
        public int Id { get; set; }
        public string Words { get; set; }
        public int HardLevel { get; set; }
        public string Gamer { get; set; }
        public DateTime? CreateDate { get; set; }
    }
}