// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TUTOR.Repository.EF
{
    public partial class StudentAnswerLog
    {
        public int Id { get; set; }
        public int? StudentId { get; set; }
        public string QuestionType { get; set; }
        public string QuestionNumber { get; set; }
        public string AnswerLog { get; set; }
        public string CostTime { get; set; }
        public int? Status { get; set; }
        public DateTime? AnswerDate { get; set; }
    }
}